# Generated by Django 4.2.29 on 2026-03-12 14:23

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0005_appointment_payment_method_appointment_payment_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_reference', models.CharField(help_text='Unique payment reference number', max_length=100, unique=True)),
                ('payment_type', models.CharField(choices=[('consultation', 'Consultation Fee'), ('emergency', 'Emergency Consultation'), ('follow_up', 'Follow-up Appointment'), ('prescription', 'Prescription Fee'), ('report', 'Medical Report'), ('other', 'Other')], default='consultation', help_text='Type of service being paid for', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in local currency', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', help_text='Payment currency (ISO 4217 code)', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], db_index=True, default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe Payment Intent ID', max_length=255, null=True, unique=True)),
                ('stripe_payment_method_id', models.CharField(blank=True, help_text='Stripe Payment Method ID', max_length=255, null=True)),
                ('stripe_charge_id', models.CharField(blank=True, help_text='Stripe Charge ID', max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method used (card, wallet, etc.)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Additional payment description')),
                ('receipt_email', models.EmailField(blank=True, help_text='Email address for receipt', max_length=254)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount refunded', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('refund_reason', models.TextField(blank=True, help_text='Reason for refund')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp when payment was completed', null=True)),
                ('appointment', models.ForeignKey(help_text='Associated appointment for this payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='doctors.appointment')),
                ('doctor', models.ForeignKey(help_text='Doctor receiving the payment', on_delete=django.db.models.deletion.CASCADE, related_name='received_payments', to='doctors.doctor')),
                ('patient', models.ForeignKey(help_text='Patient making the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(help_text='Unique invoice number', max_length=50, unique=True)),
                ('patient_name', models.CharField(help_text="Patient's full name", max_length=200)),
                ('patient_email', models.EmailField(help_text="Patient's email address", max_length=254)),
                ('doctor_name', models.CharField(help_text="Doctor's full name", max_length=200)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total invoice amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', help_text='Invoice currency', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='draft', max_length=20)),
                ('issue_date', models.DateField(default=django.utils.timezone.now, help_text='Invoice issue date')),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('paid_date', models.DateField(blank=True, help_text='Date when invoice was paid', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional invoice notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(help_text='Associated appointment', on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='doctors.appointment')),
                ('payment', models.OneToOneField(blank=True, help_text='Associated payment record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(help_text='Unique transaction identifier', max_length=100, unique=True)),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('partial_refund', 'Partial Refund'), ('transfer', 'Transfer'), ('fee', 'Processing Fee'), ('chargeback', 'Chargeback')], help_text='Type of transaction', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Transaction currency', max_length=3)),
                ('external_reference', models.CharField(blank=True, help_text='External system reference (Stripe, PayPal, etc.)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Transaction description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional transaction metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the transaction was processed')),
                ('payment', models.ForeignKey(help_text='Associated payment record', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['payment', 'transaction_type'], name='payments_tr_payment_2793b0_idx'), models.Index(fields=['transaction_type', 'processed_at'], name='payments_tr_transac_8d2d07_idx'), models.Index(fields=['external_reference'], name='payments_tr_externa_22e017_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_method_id', models.CharField(help_text='Stripe Payment Method ID', max_length=255, unique=True)),
                ('payment_method_type', models.CharField(choices=[('card', 'Credit/Debit Card'), ('bank_account', 'Bank Account'), ('digital_wallet', 'Digital Wallet'), ('other', 'Other')], help_text='Type of payment method', max_length=20)),
                ('brand', models.CharField(blank=True, help_text='Card brand (visa, mastercard, etc.)', max_length=50)),
                ('last_four', models.CharField(blank=True, help_text='Last four digits of card', max_length=4)),
                ('exp_month', models.PositiveIntegerField(blank=True, help_text='Card expiration month', null=True)),
                ('exp_year', models.PositiveIntegerField(blank=True, help_text='Card expiration year', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default payment method')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment method is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this payment method', on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='payments_pa_user_id_bd2d73_idx'), models.Index(fields=['user', 'is_default'], name='payments_pa_user_id_61fd94_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['patient', 'status'], name='payments_pa_patient_79c5d9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['doctor', 'status'], name='payments_pa_doctor__90e0cf_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['appointment', 'status'], name='payments_pa_appoint_6c6442_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_payment_intent_id'], name='payments_pa_stripe__6fe52c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_reference'], name='payments_pa_payment_87c4c1_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='payments_in_status_68daea_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['patient_email', 'status'], name='payments_in_patient_5c35c9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='payments_in_issue_d_007d09_idx'),
        ),
    ]
