# Generated by Django 4.2.29 on 2026-03-12 14:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, help_text='Full name of the user', max_length=200)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], help_text='Gender', max_length=1)),
                ('phone', models.CharField(blank=True, help_text='Primary contact phone number (e.g., +91 9876543210, (555) 123-4567)', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number can contain digits, spaces, dashes, parentheses, and + sign. Examples: +91 9876543210, (555) 123-4567, 555-123-4567', regex='^[\\+\\(]?[0-9][\\d\\s\\-\\(\\)]*$')])),
                ('alternate_phone', models.CharField(blank=True, help_text='Alternate contact phone number (e.g., +91 9876543210, (555) 123-4567)', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number can contain digits, spaces, dashes, parentheses, and + sign. Examples: +91 9876543210, (555) 123-4567, 555-123-4567', regex='^[\\+\\(]?[0-9][\\d\\s\\-\\(\\)]*$')])),
                ('address_line1', models.CharField(blank=True, help_text='Address line 1', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Address line 2 (optional)', max_length=255)),
                ('city', models.CharField(blank=True, help_text='City', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State/Province', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20)),
                ('country', models.CharField(default='India', help_text='Country', max_length=100)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Blood group', max_length=3)),
                ('allergies', models.TextField(blank=True, help_text='Known allergies (separate with commas)')),
                ('chronic_conditions', models.TextField(blank=True, help_text='Chronic medical conditions')),
                ('medications', models.TextField(blank=True, help_text='Current medications')),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Emergency contact person name', max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Emergency contact phone number (e.g., +91 9876543210, (555) 123-4567)', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number can contain digits, spaces, dashes, parentheses, and + sign. Examples: +91 9876543210, (555) 123-4567, 555-123-4567', regex='^[\\+\\(]?[0-9][\\d\\s\\-\\(\\)]*$')])),
                ('emergency_contact_relation', models.CharField(blank=True, help_text='Relationship with emergency contact', max_length=100)),
                ('profile_picture', models.ImageField(default='users/profiles/default.png', help_text='Profile picture', upload_to='users/profiles/%Y/%m/')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('sms_notifications', models.BooleanField(default=True, help_text='Receive SMS notifications')),
                ('occupation', models.CharField(blank=True, help_text='Current occupation', max_length=200)),
                ('insurance_provider', models.CharField(blank=True, help_text='Health insurance provider', max_length=200)),
                ('insurance_number', models.CharField(blank=True, help_text='Health insurance policy number', max_length=100)),
                ('last_appointment_date', models.DateTimeField(blank=True, help_text='Date of last appointment', null=True)),
                ('total_appointments', models.PositiveIntegerField(default=0, help_text='Total number of appointments booked')),
                ('is_phone_verified', models.BooleanField(default=False, help_text='Whether phone number is verified')),
                ('is_email_verified', models.BooleanField(default=False, help_text='Whether email is verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
