# Generated by Django 4.2.29 on 2026-03-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture_blob",
            field=models.BinaryField(
                blank=True, help_text="Profile picture stored in SQLite", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture_mime",
            field=models.CharField(
                blank=True,
                help_text="Mime type of the SQLite profile picture",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                default="users/profiles/default.png",
                help_text="Legacy Profile picture field",
                upload_to="users/profiles/%Y/%m/",
            ),
        ),
    ]
