# Generated by Django 4.2.29 on 2026-03-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_appointment_payment_method_appointment_payment_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_on_duty',
            field=models.BooleanField(default=True, help_text='Whether the doctor is currently on duty (Work Mode)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='lunch_break_end',
            field=models.TimeField(blank=True, help_text='End time of daily lunch break', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='lunch_break_start',
            field=models.TimeField(blank=True, help_text='Start time of daily lunch break', null=True),
        ),
    ]
