# Generated by Django 4.2.29 on 2026-03-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_doctor_is_on_duty_doctor_lunch_break_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_remarks',
            field=models.TextField(blank=True, help_text="Doctor's final remarks and prescriptions"),
        ),
        migrations.AddField(
            model_name='appointment',
            name='next_appointment_date',
            field=models.DateField(blank=True, help_text='Recommended date for follow-up', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='next_appointment_time',
            field=models.TimeField(blank=True, help_text='Recommended time for follow-up', null=True),
        ),
    ]
