# Generated by Django 4.2.29 on 2026-03-13 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_appointment_consultation_remarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the medication', max_length=200)),
                ('dosage', models.CharField(help_text='Dosage (e.g., 500mg)', max_length=100)),
                ('frequency', models.CharField(help_text='Frequency (e.g., 1-0-1)', max_length=100)),
                ('duration', models.CharField(help_text='Duration (e.g., 5 days)', max_length=100)),
                ('notes', models.CharField(blank=True, help_text='Additional instructions', max_length=255)),
                ('appointment', models.ForeignKey(help_text='Associated appointment', on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='doctors.appointment')),
            ],
        ),
    ]
