# Generated by Django 4.2.29 on 2026-03-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0008_medication"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="photo_blob",
            field=models.BinaryField(
                blank=True, help_text="Doctor photo stored in SQLite", null=True
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="photo_mime",
            field=models.CharField(
                blank=True,
                help_text="Mime type of the SQLite doctor photo",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Legacy Professional photo",
                null=True,
                upload_to="doctors/photos/%Y/%m/",
            ),
        ),
    ]
