# Generated by Django 4.2.29 on 2026-03-23 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_doctor_photo_blob_doctor_photo_mime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='recommended_doctor',
            field=models.ForeignKey(blank=True, help_text='Optional referral to another doctor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_appointments', to='doctors.doctor'),
        ),
    ]
