# Generated by Django 4.2.29 on 2026-03-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_appointment_recommended_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='frequency',
        ),
        migrations.AddField(
            model_name='medication',
            name='amount',
            field=models.CharField(default='', help_text='Amount (Total Quantity)', max_length=100),
        ),
        migrations.AddField(
            model_name='medication',
            name='eating_quantity',
            field=models.CharField(default='', help_text='Eating Quantity/Frequency (e.g., 1-0-1)', max_length=100),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(default='', help_text='Dosage Amount (e.g., 500mg)', max_length=100),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(help_text='Medicine Name', max_length=200),
        ),
    ]
