# Generated by Django 4.2.29 on 2026-03-23 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_remove_medication_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(help_text='Name of the test (e.g., CT Scan, X-Ray, Blood Test)', max_length=200)),
                ('report_file', models.FileField(help_text='Uploaded PDF report', upload_to='consultations/reports/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(help_text='Associated appointment', on_delete=django.db.models.deletion.CASCADE, related_name='test_reports', to='doctors.appointment')),
            ],
            options={
                'verbose_name': 'Test Report',
                'verbose_name_plural': 'Test Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
