# Generated by Django 4.2.29 on 2026-03-31 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_remove_appointment_unique_doctor_appointment_slot_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
